services:
  - type: web
    name: shipmate-logistics
    env: static
    buildCommand: ""
    staticPublishPath: "."
    routes:
      - type: redirect
        source: /about.html
        destination: /about
      - type: redirect
        source: /services.html
        destination: /services
      - type: redirect
        source: /fleet.html
        destination: /fleet
      - type: redirect
        source: /contact.html
        destination: /contact

      - type: rewrite
        source: /about
        destination: /about.html
      - type: rewrite
        source: /services
        destination: /services.html
      - type: rewrite
        source: /fleet
        destination: /fleet.html
      - type: rewrite
        source: /contact
        destination: /contact.html
